import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.9
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font Mono"

size = 16
